"""Initial migration

Revision ID: ff2831da7bf4
Revises: 4a4a28ab8c2d
Create Date: 2024-06-14 02:54:50.483390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2831da7bf4'
down_revision = '4a4a28ab8c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_id', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('backdrop_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('poster_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('poster_path')
        batch_op.drop_column('backdrop_path')
        batch_op.drop_column('tmdb_id')

    # ### end Alembic commands ###
